### PR TITLE
feat: cross-chain warriors

### PR DESCRIPTION
**Pull request by fadeev**
```
npx hardhat deploy --networks goerli,bsc-testnet
```

```
npx hardhat mint --network goerli --contract 0xFeAF74733B6f046F3d609e663F667Ba61B19A148

🔑 Using account: 0x2cD3D070aE1BD365909dD859d29F387AA96911e1

✅ "mint" transaction has been broadcasted to goerli
📝 Transaction hash: 0x48498d595f7aa5ab2c1569fe56b9861c4902a05420af2b7054008d1c283d8e40
🌠 Minted NFT ID: 12

Please, refer to ZetaChain's explorer for updates on the progress of the cross-chain transaction.

🌍 Explorer: https://explorer.zetachain.com/cc/tx/0x48498d595f7aa5ab2c1569fe56b9861c4902a05420af2b7054008d1c283d8e40
```

```
npx hardhat transfer --network goerli --contract 0xFeAF74733B6f046F3d609e663F667Ba61B19A148 --address 0x2cD3D070aE1BD365909dD859d29F387AA96911e1 --destination 97 --token 2 --amount 0.4
```

### CODE REVIEW

**Comment by Shepu8585** [comment]
verifie

**Review by andresaiello — APPROVED** [review]

**Comment by 12125566** [comment]
best and great

**Comment by 12125566** [comment]
welldone

**Comment by 12125566** [comment]
nice

**Comment by 12125566** [comment]
thankfull

**Comment by 12125566** [comment]
willwishes

**Comment by 12125566** [comment]
mind blowing

**Comment by phannhatthuc** [comment]
hi

**Pull request merged**
