### PR TITLE
feat(swap): add an option not to withdraw swapped ZRC20

### PR DESCRIPTION
**Pull request by fadeev**

### CODE REVIEW

**Comment by fadeev** [comment]
@andresaiello this is a proposal to extend the swap example to handle a scenario where a user wants to keep the swapped ZRC-20 asset instead of immediatly withdrawing it. This might seem odd, but I'm building an example frontend where I want users to be able to transfer/swap/withdraw/deposit all tokens to all other tokens. One of the few operations left is "deposit and swap":

Screenshot 2023-11-14 at 13 03 43

Want to know your opinion on this. Even though not withdrawing might seem odd (most users will want to withdraw), having this swap component talk to this example contract would make it component also a demo of the example contract.

**Comment by fadeev** [comment]
@andresaiello another question I have is adapting `bytesToAddress` function to work with `bytes memory`:

https://github.com/zeta-chain/example-contracts/blob/7dab1a4888ab5e159c889e0bd274f651ac9aefbe/omnichain/swap/contracts/Swap.sol#L28-L39

Of course, we already have a helper for this, but it's only for `calldata`, not `memory`:

https://github.com/zeta-chain/toolkit/blob/a902bea0581b284a59d66a2c9ae547d3b0cdc93c/contracts/BytesHelperLib.sol#L15-L23

Would it be a good idea to add the `bytes memory` version as another helper (if so, do you have any suggestions on the name), and if not, what's the better way to handle this.

**Comment by andresaiello** [comment]
> bytesToAddress

good idea. I didn't need it yet but looks like someone may need it. Let's just call it bytesMemoryToAddress

**Comment by fadeev** [comment]
@andresaiello wdyt about the changes to contract in general? The ability to not withdraw tokens during swap may seem a bit niche, but it has a few advantages: it matches the requirements of the example frontend (to be able to swap gas/ERC-20 to ZRC-20 without withdrawing) and uses the same pattern of `action` as in staking. Maybe this means we even need to change the default template to use `action`, because it might be common for omnichain contracts to be able to execute different logic from the same `onCrossChainCall`.

**Comment by fadeev** [comment]
We need to update this PR to be compatible with the code as it is in the `main` branch.

**Comment by fadeev** [comment]
Going to implement this next as a third part of the swap tutorial:

* Basic
* With ZETA
* With not withdrawals

To simplify things I'm probably not going to use an `action` integer prefix, but add it as an optional last argument in the message.

**Pull request closed without merging**
