### PR TITLE
test(swap): add test cases

### PR DESCRIPTION
**Pull request by lukema95**
Ref: #14 
Usage:
```shell
npx hardhat test ./test/Swap.spec.ts --network localhost
```

### CODE REVIEW

**Comment by fadeev** [comment]
@andresaiello please, take a look.

**Comment by fadeev** [comment]
@lukema95 I think this looks really cool! We can expand this to other contracts and then extract the shared functionality (helper contracts and TS functions) into the toolkit.

**Review by fadeev — APPROVED** [review]

**Comment by lukema95** [comment]
> @lukema95 I think this looks really cool! We can expand this to other contracts and then extract the shared functionality (helper contracts and TS functions) into the toolkit.

Sure, 

> @lukema95 I think this looks really cool! We can expand this to other contracts and then extract the shared functionality (helper contracts and TS functions) into the toolkit.

same idea😄

**Comment by lukema95** [comment]
> @lukema95 I think this looks really cool! We can expand this to other contracts and then extract the shared functionality (helper contracts and TS functions) into the toolkit.

I have submitted a PR, and once it's merged, I will modify the code to make it dependent on the test utility classes of this code repository. 
PR: [Add test dependency contracts] (https://github.com/zeta-chain/toolkit/pull/104)

**Review by andresaiello — APPROVED** [review]

**Pull request merged**
